import Config

# Use PostgreSQL in production
config :zentinel_cp, ecto_adapter: Ecto.Adapters.Postgres

# Use Postgres engine for Oban in production
config :zentinel_cp, Oban, engine: Oban.Engines.Basic

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :zentinel_cp, ZentinelCpWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force SSL in production (opt-in via FORCE_SSL=true at build time).
# Sets the "strict-transport-security" header (HSTS) and redirects HTTP → HTTPS.
# Note: `force_ssl` must be set at compile-time.
if System.get_env("FORCE_SSL") in ["true", "1"] do
  config :zentinel_cp, ZentinelCpWeb.Endpoint,
    force_ssl: [
      rewrite_on: [:x_forwarded_proto],
      exclude: ["localhost", "127.0.0.1"]
    ]
end

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Use structured JSON logging in production
config :logger, :default_handler, formatter: {LoggerJSON.Formatters.Basic, []}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
